import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const SOURCE = 'https://kafka.monster/cs/';
const OUTPUT = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'catalog-live.generated.js');

function decodeHtml(value) {
  return value
    .replace(/&#x([0-9a-f]+);/gi, (_, code) => String.fromCodePoint(Number.parseInt(code, 16)))
    .replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(Number(code)))
    .replace(/&nbsp;/gi, ' ')
    .replace(/&amp;/gi, '&')
    .replace(/&quot;/gi, '"')
    .replace(/&#39;|&apos;/gi, "'")
    .replace(/&lt;/gi, '<')
    .replace(/&gt;/gi, '>');
}

function cleanLabel(html) {
  return decodeHtml(html.replace(/<[^>]*>/g, ' ')).replace(/\s+/g, ' ').trim();
}

function parseCategoryTree(sectionHtml) {
  const roots = [];
  const listStack = [roots];
  let rootListSeen = false;
  const tokens = sectionHtml.matchAll(/<ul\b[^>]*>|<\/ul>|<a\b[^>]*href=(['"])(.*?)\1[^>]*>([\s\S]*?)<\/a>/gi);

  for (const match of tokens) {
    const token = match[0];
    if (/^<ul\b/i.test(token)) {
      if (!rootListSeen) {
        rootListSeen = true;
      } else {
        const current = listStack.at(-1);
        const parent = current?.at(-1);
        if (parent) listStack.push(parent.children);
      }
      continue;
    }
    if (/^<\/ul/i.test(token)) {
      if (listStack.length > 1) listStack.pop();
      continue;
    }

    const name = cleanLabel(match[3]);
    if (!name) continue;
    listStack.at(-1).push({
      name,
      url: new URL(decodeHtml(match[2]), SOURCE).href,
      children: []
    });
  }

  return roots;
}

const response = await fetch(SOURCE, {
  headers: { 'user-agent': 'KafkaCatalogSync/1.0 (+local prototype)' }
});
if (!response.ok) throw new Error(`Kafka Monster returned HTTP ${response.status}`);

const html = await response.text();
const sectionStart = html.indexOf('<section class="blockcategories_footer');
const sectionEnd = html.indexOf('</section>', sectionStart);
if (sectionStart < 0 || sectionEnd < 0) throw new Error('Category footer was not found in the live page.');

const categories = parseCategoryTree(html.slice(sectionStart, sectionEnd));
if (!categories.length) throw new Error('No live categories were parsed.');

const snapshot = {
  source: SOURCE,
  fetchedAt: new Date().toISOString(),
  categories
};
const output = `/* Generated by scripts/scrape-catalog.mjs. Do not edit by hand. */\n` +
  `(function () { 'use strict'; window.kafkaLiveCatalogSnapshot = Object.freeze(${JSON.stringify(snapshot, null, 2)}); })();\n`;

await writeFile(OUTPUT, output, 'utf8');
console.log(`Wrote ${categories.length} categories to ${OUTPUT}`);
